### Bar charts of person centred care PREMs from December 2025

```{r prembarcharts}

if (exists("page_group")) {
  storyIDs = storyFrame$PostID[storyFrame$NACSgroup == page_group]
  premFrame_group <- premFrame[premFrame$PostID %in% storyIDs,]
} else{
  premFrame_group <- premFrame
}

prem_pct = premFrame_group %>% 
  mutate(premScoreText = case_when(premScoreText == "Strongly agree" ~ "Agree",
                                   premScoreText == "Strongly disagree" ~ "Disagree",
                                   TRUE ~ premScoreText)) %>% 
  count(premQ, premScoreText) %>% 
  group_by(premQ) %>% 
  mutate(pct = n/sum(n),
         pct_lbl = scales::percent(pct, accuracy = 1)) %>% 
  ungroup()

if (nrow(premFrame_group) > 0) {
  
bars = ggplot() +
  geom_bar(
    data = premFrame_group,
    aes(y = premQ, fill = premScoreText),
    position = position_likert(), # This centers the data 
    stat = "prop",
    complete = "fill" # This centers it around 0
  ) +
  geom_text(aes(y = 6.45, x = 1.05, label = "Total\nagree"), size = 3) +
  geom_text(
    data = filter(prem_pct, premScoreText == "Agree"),
    aes(y = premQ, x = 1.05, label = pct_lbl),
    size = 3
  ) +
  geom_text(aes(y = 6.45, x = -1.05, label = "Total\nDisagree"), size = 3) +
  geom_text(
    data = filter(prem_pct, premScoreText == "Disagree"),
    aes(y = premQ, x = -1.05, label = pct_lbl),
    size = 3
  ) +
  geom_text(
    data = filter(prem_pct,  premScoreText == "Neither agree nor disagree", pct > 0.1),
    aes(y = premQ, x = 0, label = pct_lbl)    ,
    size = 3
  ) +
  scale_x_continuous(label = label_percent_abs(), expand = expansion(mult = c(0.1, 0.1))) +
  scale_y_discrete(limits = rev, expand = expansion(add = c(0, 0.8)))+
  scale_fill_manual(
    values = c("#753640","#d86477","#D5E2E9","#ADCEA1","#7D9575"),
    name = ""
  )+
  labs(
    x = "Percentage",
    y = ""
  ) +
  theme_minimal()+
  theme(axis.text.y = element_text(size=11),
        panel.grid.major.y = element_blank())
  

b2 = plotly::ggplotly(bars) %>% 
      style(hoverinfo = "none")
  

if (exists("page_group")) {
  b2 <- b2 %>%
    layout(showlegend = FALSE)
}

b2$x$data[[6]]$text <- "<b>Total<br>agree</b>"
b2$x$data[[8]]$text <- "<b>Total<br>disagree</b>"

b2
} else {cat("Not enough data")}
```

`r if(exists("page_group")) {"<!--"}`
------------------------------------------------------------------------
  
**What are the person centred care PREMs?**
  
These six person centred care Patient Reported Experience Measures (PREMs) have been codesigned for Excellence in Care (EiC), with significant contributions from subject-matter experts, service users and patient experience leads. The PREMs offer a practical way of assessing whether care delivery reflects person-centred principles - personalisation, coordination, enablement, wellbeing, and experience of care.

These charts show the range of agreement with the PREM statements. They're centred around a neutral zero-line to make comparison across measures easier. 'Total agree' is the percentage who agree or strongly agree. 'Total disagree' is the percentage who disagree or strongly disagree.

These charts are based on `r nrow(distinct(premFrame_group, PostID, service))` responses.
`r if(exists("page_group")) {"-->"}`

### `r ifelse(exists("page_group"),"Run chart of median overall PREM score" ,"Run charts of median person centred care PREMs")`

```{r premruncharts}

if (exists("page_group")) {
  
  # Overall PREM score chart for specialty tabs
  storyIDs = storyFrame$PostID[storyFrame$NACSgroup == page_group]
  premFrame_group <- premFrame[premFrame$PostID %in% storyIDs,]
  
  if (nrow(premFrame_group) > 0) {  
    df <- premFrame_group %>% 
      #Sum scores for each service within a post
      summarise(aggscore = sum(as.numeric(premScoreText)),
                n = n(),
                .by = c(Month, PostID, service)) %>% 
      #Only include when all 6 questions have been answered
      filter(n == 6) %>% 
      # Calculate median for total PREM score
      summarise(observation = median(aggscore), 
                .by = Month) %>%
      # Format Month as a date
      mutate(date = as.Date(paste0("20",substr(Month,1,2), "-", substr(Month,4,5),"-01")))
    
    rc = df %>%
      #make_runchart() %>%
      ggplot()+
      geom_line(aes(x = date, y = observation))+
      geom_point(aes(x = date, y = observation))+
      theme_minimal()+
      theme(axis.text.x=element_text(angle = 90, hjust = 0),
            panel.grid.minor = element_blank())+
      scale_x_date(date_labels = "%Y-%m", date_breaks = "1 month") +
      #scale_y_continuous(limits = c(min(df$observation),5), breaks = seq(0, 5, 0.5),)+
      scale_y_continuous(limits = c(min(min(df$observation),20),30), breaks = c(0,21,24,27,30))+
      labs(x = "", y= "Overall score")
    
    plotly::ggplotly(rc)
    
  } else {cat("Not enough data")}
  
} else {
  
  # Median PREM score charts for each question (item) if not specialty tab
  premFrame_group <- premFrame
  
  if (nrow(premFrame_group) > 0) {
    
    Qs = levels(premFrame$premQ)
    
    linefun <- function(n){
      df <- premFrame_group %>%
        filter(premQ == Qs[n]) %>%
        group_by(Month, premQ) %>%
        summarise(observation = median(as.numeric(premScoreText))) %>%
        ungroup() %>%
        mutate(date = as.Date(paste0("20",substr(Month,1,2), "-", substr(Month,4,5),"-01")))
      
      rc = df %>%
        #make_runchart() %>%
        ggplot()+
        geom_line(aes(x = date, y = observation))+
        geom_point(aes(x = date, y = observation))+
        theme_minimal()+
        theme(axis.text.x=element_text(angle = 90, hjust = 0))+
        scale_x_date(date_labels = "%Y-%m", date_breaks = "1 month") +
        scale_y_continuous(limits = c(min(df$observation),5), breaks = seq(0, 5, 0.5),)+
        labs(x = "")
      
      plotly::ggplotly(rc) %>%
        layout(annotations = list(text = Qs[n],
                                  x = -0.1 , y = 0.5,
                                  xanchor = "right",
                                  align = "right",
                                  showarrow = F,
                                  xref='paper',
                                  yref='paper'),
               margin = list(l = 600))
    }
    
    subplot(linefun(1), linefun(2), linefun(3), linefun(4), linefun(5), linefun(6), nrows = 6, shareX = TRUE)
    
  } else {cat("Not enough data")}
}


```

`r if(exists("page_group")) {"<!--"}`
------------------------------------------------------------------------
  
**What are the person centred care PREMS?**
  
These six person centred care Patient Reported Experience Measures (PREMs) have been codesigned for Excellence in Care (EiC), with significant contributions from subject-matter experts, service users and patient experience leads. The PREMs offer a practical way of assessing whether care delivery reflects person-centred principles - personalisation, coordination, enablement, wellbeing, and experience of care.

These charts show how the monthly median score for each measure changes over time. Median scores for each measure can be interpreted as follows.

<style>
.prem-table table {
  border-collapse: collapse;
  width: 100%;
}

.prem-table td, 
.prem-table th {
  border-top: 1px solid #dddddd;
  border-bottom: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}
</style>

<div class="prem-table">
<table>
  <tr>
    <th>Median score</th>
    <th>Interpretation</th>
    <th>Suggested action</th>
  </tr>
  <tr>
    <td>≥4.5</td>
    <td>Excellent person-centred care</td>
    <td>Sustain and share learning</td>
  </tr>
  <tr>
    <td>4–4.49</td>
    <td>Good person-centred care</td>
    <td>Consolidate and strengthen</td>
  </tr>
  <tr>
    <td>3.5–3.99</td>
    <td>Person-centred care may need improvement</td>
    <td>Prioritise targeted improvement</td>
  </tr>
  <tr>
    <td><3.5</td>
    <td>Priority to improve person-centred</td>
    <td>Immediate improvement planning</td>
  </tr>
</table>
</div>
`r if(exists("page_group")) {"-->"}`